### ISSUE TITLE
Review: Popover.anchorOrigin

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#11]
`popover.anchorOrigin`, and `popover.transformOrigin` are both implemented like this:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Props.fs#L3120-L3142

The usage is then:

```f#
popover.anchorOrigin.topLeft
popover.anchorOrigin.custom(50, 80)
popover.anchorOrigin.customLeft(30)
popover.anchorOrigin.topCustom(90)
```

Does that design make sense?

My only gripe is that it's not immediately clear without looking at the parameter name (or the other member names) which is which when it comes to `centerCustom` and `customCenter`. Personally I can live with that since, as mentioned, both the parameter name and the other names make that clear.

**Comment by Zaid-Ajaj** [comment]
> Does that design make sense?

I guess it looks fine, though I would simplify `popover.anchorOrigin.custom(50, 80)` to just `popover.anchorOrigin(50, 80)` when possible, as for the other ones, I think they are OK but I would need to try them out (they probably won't be as useful as the first predefined 9 combinations)

**Comment by cmeeren** [comment]
> I would simplify `popover.anchorOrigin.custom(50, 80)` to just `popover.anchorOrigin(50, 80)` when possible

Agreed.

> as for the other ones, I think they are OK but I would need to try them out (they probably won't be as useful as the first predefined 9 combinations)

An alternative syntax would be e.g.

```f#
popover.anchorOrigin(PopoverAnchorOriginHorizontal.Top, 25)
popover.anchorOrigin(10, PopoverAnchorOriginVertical.Top)
```

The name of the `StringEnum` might be shorter, but the allowed values are component-specific. For example, `badge.anchorOrigin` does not have `Center` (neither vertical nor horizontal). Granted, `badge.anchorOrigin` has only predefined values, so it's a moot point. But one could imagine new components/props being added, so it would still be safest to use StringEnum type names specific to component, prop, and argument.

Personally, given the above, I like the existing solution better, but I am open to counter-arguments.

**Comment by Zaid-Ajaj** [comment]
I like the alternative syntax because even though the names might be different, it is move obvious what the code is doing (or what is it mapping to) in comparison with the `topCustom` etc.
