### ISSUE TITLE
Review: ParamArray props

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#13]
I have implemented some props using `ParamArray` where I think it's likely that users might want to use a statically defined list of values. Examples:

### `tablePagination.rowsPerPageOptions`

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Props.fs#L4709

Usage:

```f#
tablePagination.rowsPerPageOptions(5, 10, 20, 50, 100)
```

### `hidden.only`

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Props.fs#L1937

Usage:

```f#
hidden.only(BreakpointKey.Xs, BreakpointKey.Sm)
```

There are currently no extra overloads for these props (i.e., no `list` overloads).

Does the design seem sound?

**Comment by Zaid-Ajaj** [comment]
These look good! Though it would be nice to add `list` overloads but again, in the early versions you could try only these out and see what users think

**Comment by cmeeren** [comment]
Thanks! I'll wait until someone actually requests `list` overloads.
