### ISSUE TITLE
Review: ICssUnit props

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#15]
I have implemented some props accepting e.g. `"5rem"` as accepting `ICssUnit`, since my understanding is that `ICssUnit` is basically just a stand-in for a correctly formatted string.

Examples:

https://github.com/cmeeren/Feliz.MaterialUI/blob/4bb895bad20efc55afdfa0def9a31f623e61c322/src/Feliz.MaterialUI/Props.fs#L753-L754

https://github.com/cmeeren/Feliz.MaterialUI/blob/4bb895bad20efc55afdfa0def9a31f623e61c322/src/Feliz.MaterialUI/Props.fs#L819-L820

https://github.com/cmeeren/Feliz.MaterialUI/blob/4bb895bad20efc55afdfa0def9a31f623e61c322/src/Feliz.MaterialUI/Props.fs#L819-L820

Usage:

```f#
circularProgress.size (length.px 24)
```

Does that make sense?

**Comment by Zaid-Ajaj** [comment]
> Does that make sense?

Yes, that is how Feliz does its CSS units

**Comment by cmeeren** [comment]
Thanks! :)
