### ISSUE TITLE
Review: Element in ref props vs. more specific elements (HTMLInputElement etc.)

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#16]
Some ref props are implemented using e.g. `IRefValue<HtmlInputElement option>`:

https://github.com/cmeeren/Feliz.MaterialUI/blob/4bb895bad20efc55afdfa0def9a31f623e61c322/src/Feliz.MaterialUI/Props.fs#L652

I have used a specific `Element` type here because the documentation for this prop says that:

> This prop can be used to pass a ref to the `input` element.

However, some components, such as `Input` ([API docs](https://material-ui.com/api/input/)), also have an `inputComponent` prop that can be used to change the underlying component. Wouldn't that mean that if you use a ref, it might not be an `input` element, and thus that `HTMLInputElement` is incorrect?

If so, would it be safer to just use `Element` (or perhaps `HTMLElement`?) and let the user decide themselves which `Element` they want to assume it is at runtime?

The same goes for the `ButtonBase` component, where I have currently used `HTMLButtonElement`, but which also supports changing the underlying component.

**Comment by Zaid-Ajaj** [comment]
> Wouldn't that mean that if you use a ref, it might not be an input element, and thus that HTMLInputElement is incorrect?

I guess so, maybe use both generic *and* specific as overloads of `inputRef`?
```fs
static member inline inputRef(ref: IRefValue<HTMLInputElement option>) = Interop.mkAttr "inputRef" ref 
static member inline inputRef(ref: IRefValue<HTMLElement option>) = Interop.mkAttr "inputRef" ref 
static member inline inputRef(ref: IRefValue<Element option>) = Interop.mkAttr "inputRef" ref 

```

**Comment by cmeeren** [comment]
I think that might cause issues for overload resolution (but haven't tested). Also I don't really see how the more-specific overloads help the user.
