### ISSUE TITLE
Drop the -alpha prelease in favor of 0.0.1?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [cmeeren/Feliz.MaterialUI#19]
It looks like having something `-alpha` makes dotnet and paket unhappy when installing the library using `dotnet add package Feliz.MaterialUI` and instead you have to provide the full version when doing so: `dotnet add package Feliz.MaterialUI --version 0.2.0-alpha` which is slightly annoying for people who want to try out the library

**Comment by cmeeren** [comment]
Fair enough, I'll try to remember it for the next release 👍

**Comment by cmeeren** [comment]
0.3.0 is in the pipeline.
