### ISSUE TITLE
Review: "Native" vs. idiomatic bindings

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#2]
(Related: https://github.com/Zaid-Ajaj/Feliz/issues/38)

AFAIK, bindings for JS-native objects by necessity needs to match the actual JS objects in order for them to be usable. For example, here is the toolbar style mixin, supposed to be spread along with other styles when using JSS:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Bindings.fs#L176-L177

Naturally, the styling DSL is based around `IStyleAttribute list`, so in order to make it interop nicely, I have to make another prop with another name like this:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Bindings.fs#L175-L179

Does that implementation and design look OK?

A similar, though different problem occurs with `Theme.spacing`. It's a function that has several overloads:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Bindings.fs#L218-L221

But at the same time, it can be set to a variety of different formats:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Bindings.fs#L225-L233

My understanding is that MUI does some magic when setting `theme.spacing` so that the functions continue to work.

Does the implementation and design above look OK?

**Comment by Zaid-Ajaj** [comment]
> Naturally, the styling DSL is based around IStyleAttribute list, so in order to make it interop nicely, I have to make another prop with another name like this:

I am not sure I understand what "to make it interop nicely" means. if `toolbar` will not be consumed from the user code (only behind the scenes) then you don't need *another* prop, just the following should suffice:
```fs
[<AbstractClass; Erase>] 
type Mixins = 
   [<Emit("Object.entries($0.toolbar)")>] 
   member inline __.toolbar : IStyleAttribute [] = jsNative 
```

>  bindings for JS-native objects by necessity needs to match the actual JS objects in order for them to be usable

It is either the name of the property that has to match or the name you use in `Emit`: which is what you are doing in `toolbarStyle` so you might as well change it to the snippet above (remove `toolbar : obj` and replace instead with `toolbar : IStyleAttribute []` plus the emit expression) 

Please correct me if I misunderstood the problem

**Comment by cmeeren** [comment]
Thanks! You're right, I didn't think of using `Emit` like that. I don't think the "native" `Mixins.toolbar` will ever need to be consumed from user code, so I think your suggestion is better.

It seems `tpacing` is another beast, though?

**Comment by Zaid-Ajaj** [comment]
Hmm this `spacing` thing is weird because it is used differently in `Theme` *creation* vs. *usage*. I think it is better to have a separate API for creating the theme and another for consuming it. I try to come up with an example implementation

**Comment by cmeeren** [comment]
As mentioned in https://github.com/cmeeren/Feliz.MaterialUI/issues/30#issuecomment-553272658, we need a proper theme creation/customization DSL.

Challenges:

* The DSL needs to support both creating a (partial) theme from scratch (essentially `unit -> Theme`), and for customizing an existing theme (essentially `Theme -> Theme`).
* The DSL needs to take into account (particularly for the above point) that a theme objects can look different when it's passed from MUI than when it's created. For example, `theme.palette.primary`, `.secondary` etc. can be set to Color objects or PaletteIntention objects, but when passed from MUI, they will always be PaletteIntention (see https://github.com/cmeeren/Feliz.MaterialUI/issues/30#issuecomment-553272658).

**Comment by Shmew** [comment]
Similar to what I proposed in [Clean up memo overloads](https://github.com/Zaid-Ajaj/Feliz/issues/118), what do you think of some sort of feeder function? I don't think that style of option input scales very well when things start to become nested though.

Alternatively what if we just model the actual Theme object and then you can create the overrides similar to how you set props with everything else? This would look something like:

```fsharp
let getTheme themeType = 
    Styles.createMuiTheme [
        Theme.paletteType.dark
        Theme.palettePrimary [
            palettePrimary.dark "#fff"
            palettePrimary.main "#000"
        ]
    ]
```

**Comment by cmeeren** [comment]
> Alternatively what if we just model the actual Theme object and then you can create the overrides similar to how you set props with everything else? This would look something like:

Thanks! Yes, that is actually what I have been thinking about. I aim to experiment a bit and write some client code that uses such a DSL to see if it's nice to use. Unfortunately, my capacity is limited at the moment, and I can't promise when I'll be able to get to it. If you want to help out, feel free to experiment!

**Comment by cmeeren** [comment]
Based on the MUI [Default Theme docs](https://material-ui.com/customization/default-theme/), here's some considerations:

```f#
Styles.createMuiTheme [
  theme.palette [
    palette.error [
      // deeply nested, and rather generic name
      error.main "#f44336"
    ]
  ]
  theme.typography [
    // clashes with typography prop
    typography.h1 [
      // deeply nested, and rather generic name
      h1.fontFamily "Roboto"
    ]
  ]
]
```

I have a couple of problems with a syntax like the above:

1. The props are deeply nested. Not in itself a big problem, though.
2. The names can become rather generic, increasing the chance for name collision. Or they could collide outright, e.g. `typography`, which is also a component.
3. I could rename the modules, e.g. `themeTypography.h1` instead of `typography.h1`, but then it's much less discoverable, and users would need to rely on documentation or memory to get it right. I'd like it to be as self-explanatory as possible.

Tips and opinions welcome.

**Comment by Shmew** [comment]
I like the syntax in your code snippet. Yeah it involves some trickery, but that's on the library end which is something you (hopefully) only write once. From that point on it's nice and easy for people to consume. You also then don't have to worry about namespace collisions. If the goal is end-user friendliness I don't see how any other style could be better.

You can also do it similar to how it's done now, but with it being more sugared rather than having to use `jsOption`.

**Comment by cmeeren** [comment]
Perhaps I should have been clearer. The syntax in the code snippet I just posted doesn't involve any trickery. It's straightforward, but the problem is name collisions (to be exact, it's module names, not namespaces). For example, there will be a `typography` module both for the theme (containing `h1` etc. as shown) as well as the `typography` prop module when defining components.

The trickery comes into play in *your* code snippet, where you suggest `Theme.palettePrimary [...]`, but that single call would have to set up a two-level object: `{ palette: { primary: { ... } } }`. I don't know of a way to do this without potential performance impacts.

(For completeness: The method is having `Theme.palettePrimary` define a property with name `palette.primary`, and then have the object construction code scan for dots in property names and create sub-objects correspondingly. But if that is done in a tight loop, e.g. for each update, it's conceivable it'll cause performance issues. I don't know enough about React or the potential performance impact of this method to know whether it's feasible, but I'd rather err on the side of caution.)

**Comment by Shmew** [comment]
Oh, I'm sorry. Yeah I misunderstood. My code snippet up there is pretty old, it was how I was doing Feliz.Plotly bindings at the time. I switched them to how your code snippet is structured. It works for my case since the modules aren't likely to ever collide with anything else.

The only thing I can think of to solve this would be the second part of my response where the syntax of the function is something like:

```fsharp
Styles.createMuiTheme (fun theme ->
  theme.palette (fun palette ->
    palette.error (fun error ->
      // deeply nested, and rather generic name
      error.main "#f44336"
    )
  )
  theme.typography (fun typography ->
    // clashes with typography prop
    typography.h1 (fun h1 ->
      // deeply nested, and rather generic name
      h1.fontFamily "Roboto"
    )
  )
)
```

**Comment by cmeeren** [comment]
Unfortunately, since that requires instances and instance members, you can't do e.g. `theme.paletteType.dark` as an "enum prop".

@Zaid-Ajaj Do you have any suggestions? (Regarding the last 4-6 comments.)

**Comment by Shmew** [comment]
If it's creating/updating a record, and the hook returns that same object, wouldn't you be able to do that kind of syntax? The `theme` part would be whatever you named it when you did the let binding.

**Comment by cmeeren** [comment]
Sorry, I got things mixed up - what's not possible is mixed normal/enum props, e.g. `theme.paletteType.dark` as well as `theme.paletteType "custom"`. It's used for some component props; it might be needed (now or in the future) with theme props, too.

**Comment by Shmew** [comment]
I can't tell if I'm just being dense or if we're talking about different things.

For example in this snippet from one of my applications:

```fsharp
let private application = React.memo (fun (input: {| model: Model; dispatch: Msg -> unit |}) ->
    let currentTheme = React.useMemo((fun () -> AppTheme.getTheme input.model.LocalStore.DarkTheme), [| input.model.LocalStore.DarkTheme |])
    let c = AppTheme.useStyles()

    Mui.themeProvider [ 
        themeProvider.theme currentTheme
        themeProvider.children [
            React.contextProvider(Context.userInfo, input.model.UserInfo, React.fragment [
                Html.div [ 
                    prop.className c.root
                    prop.children [ 
                        Mui.cssBaseline []
                        mainAppBar input
                        drawer input
                        Html.main [ 
                            prop.className c.content
                            prop.children [ pageView input ] 
                        ]
                    ]
                ]
            ])
        ]
    ])
```

`currentTheme` is already returning an object defined via:

```fsharp
let private getTheme' themeType = Styles.createMuiTheme(jsOptions<Theme> <| fun t ->
    t.palette <-
        jsOptions<Palette> (fun p ->
            p.``type`` <- themeType.PaletteType
            p.primary <-
                !^(jsOptions<PaletteIntention> (fun pi ->
                    pi.light <- themeType.PLight
                    pi.main <- themeType.PMain
                    pi.dark <- themeType.PDark
                    pi.contrastText <- themeType.PCText))
            p.secondary <-
                !^(jsOptions<PaletteIntention> (fun pi ->
                    pi.main <- themeType.SMain
                    pi.dark <- themeType.SDark
                    if themeType.SCText.IsSome then pi.contrastText <- themeType.SCText.Value))
            p.error <-
                !^(jsOptions<PaletteIntention> (fun pi ->
                    pi.main <- themeType.EMain
                    if themeType.ECText.IsSome then pi.contrastText <- themeType.ECText.Value))
            p.contrastThreshold <- 3)

...
```

Where I would like to be able to do:

```fsharp
let private getThemeTest themeType = Styles.createMuiTheme(fun theme ->
        { theme with
            Type' = themeType.PaletteType
            Primary = 
                { theme.Primary with
                    Light = themeType.PLight
                    Main = themeType.PMain } }
    )
```

`Styles.createMuiTheme` doesn't even have to be a `Theme -> Theme` but could just accept a theme and define a `DefaultTheme`.

In both the snippets `themeType` is my own defined record that I pass in when generating my theme based on the model and other things. The snippet looks ugly now, but with optics or whatever to make composing things easier it would be nice.

**Comment by cmeeren** [comment]
Oh, right. I was talking about your snippet in https://github.com/cmeeren/Feliz.MaterialUI/issues/2#issuecomment-576030779, not the remark following it about using records.

Thank you for all the suggestions. Of everything suggested thus far, I prefer something like the "original" Feliz syntax. It's what users are used to and expecting, and I'd rather avoid a whole new DSL if possible. So perhaps I'll just have to find a way to make it work without name collisions.

**Comment by Shmew** [comment]
You're welcome! Yeah, most of the other suggestions not only diverge from the expected syntax, but are more complex. I agree, that's the best solution if feasible.

**Comment by cmeeren** [comment]
Thanks to the npm package flat and the fact that themes are relatively seldom created, I opted for the flattened prop list syntax. This is what I'll do (I have it working, only needs minor tweaks before publishing):

```f#
  let dark = Styles.createMuiTheme([
    theme.palette.type'.dark
    theme.palette.primary Colors.lightBlue
    theme.palette.secondary Colors.pink
    theme.palette.background.default' defaultTheme.palette.grey.``900``
    theme.typography.h1.fontSize "3rem"
    theme.typography.h2.fontSize "2rem"
    theme.typography.h3.fontSize "1.5rem"

    // TODO: place this under theme.overrides
    themeOverrides.muiAppBar.colorDefault [
      style.backgroundColor defaultTheme.palette.grey.A400
    ]
    themeOverrides.muiPaper.root [
      style.backgroundColor defaultTheme.palette.grey.A400
    ]
    theme.overrides.muiDrawer.paper [
      style.backgroundColor defaultTheme.palette.grey.``900``
    ]

    theme.props.muiAppBar [
      appBar.color.default'
    ]
  ])
```

The flattened syntax could conceivably also be used with the `classes` prop all components have, e.g.

```f#
appBar.classes.root "foo"
appBar.classes.positionSticky "bar"
```

instead of

```f#
appBar.classes [
  classes.appBar.root "foo"
  classes.appBar.positionSticky "bar"
]
```

However, AFAIK that would be called for each render, so I don't want to do that without knowing the performance impacts of flattening/unflattening.

**Comment by cmeeren** [comment]
At long last, I'm finally able to close this! Thanks for the tips, it's very good to have someone to share ideas with.

New theme/styling DSL released in 0.10.0.

**Comment by Zaid-Ajaj** [comment]
@cmeeren Very interesting choice for the flattened properties. really love it!

**Comment by cmeeren** [comment]
Happy to hear it! Let me know if you know anything about the performance impacts. The syntax could be used for other DSLs too (the MUI `classes` DSL as I mentioned, and for other libraries which have a more "nested" nature), but I don't know anything about how costly the unflattening is, nor do I really know how to properly investigate it or what to make of the possible results.

**Comment by Zaid-Ajaj** [comment]
flatten and unflatten are both cheap operations since it is only traversing a very small object. Not to mention that this operation is executed one time every once in a while so I think no worries there at all

**Comment by cmeeren** [comment]
Thanks!

> Not to mention that this operation is executed one time every once in a while so I think no worries there at all

I assume you are referring to creating a theme? I was thinking of using this mechanism in props, so worst-case it could be called at each render, right?

**Comment by Zaid-Ajaj** [comment]
> I assume you are referring to creating a theme? I was thinking of using this mechanism in props, so worst-case it could be called at each render, right?

Yeah which would be still be plenty fast

**Comment by cmeeren** [comment]
Thanks, good to hear. 👍

**Comment by Shmew** [comment]
Awesome work @cmeeren!
