### ISSUE TITLE
Compiler error when using Mui.listItem

### ISSUE THREAD

**Issue by Shmew** [cmeeren/Feliz.MaterialUI#23]
```
FSC : error FS0193: The module/namespace 'React' from compilation unit 'Feliz' did not contain the val 'ValLinkagePartialKey(toArray)' [C:\...\Client.fsproj]
Fsc: FSC(0,0): error FS0193: The module/namespace 'React' from compilation unit 'Feliz' did not contain the val 'ValLinkagePartialKey(toArray)'
```

This gets thrown when I have the following:

```
namespace Client

module View =
    open Elmish
    open Feliz
    open Feliz.MaterialUI
    open Feliz.Router
    open Types
        

    let pageListItem model dispatch =
        Mui.listItem [
            listItem.children [
                Html.div ""
            ]
        ]
        
    let application = React.functionComponent(fun (model, (dispatch: (Msg -> unit))) ->
        Html.div "")

    let render (model: Model) dispatch =
        Router.router [
            Router.application (application (model, dispatch))
        ]
```

Which is weird because I just had it working, but I can't seem to figure out the issue

Looking further it seems like it's any Mui.x component when given children that are specific to that type results in this error.

**Comment by Shmew** [comment]
Here is a reproduction

https://github.com/Shmew/ErroRepro

**Comment by cmeeren** [comment]
@Zaid-Ajaj, the core of the issue is this:

When `children` is defined like this (inline and delegates to Feliz's `prop.children`), it fails to compile:

```f#
static member inline children(elements: ReactElement seq) = prop.children elements
```

However, if I either remove `inline`, or if I keep inline but replace `prop.children elements` with e.g. `Interop.mkAttr "children" elements`, then it compiles.

Do you have any idea why?

In any case, if we do something inheritance-based like suggested in #20 then this might disappear.

**Comment by Zaid-Ajaj** [comment]
> Do you have any idea why?

I really don't :/ weird stuff. In Feliz.Recharts, I am defining the children to take a list of elements instead of a generic `seq` like this
```fs
static member inline children (elements: Fable.React.ReactElement list) = prop.children elements
```
and this works nicely

**Comment by cmeeren** [comment]
Just to check, could you try if client code (for the function you posted) works if you use `seq` instead of `list`?

Note that the client code may need to be in a project separate from both Feliz and Feliz.Recharts.

**Comment by Zaid-Ajaj** [comment]
I am using the in [docs](https://github.com/Zaid-Ajaj/Feliz/tree/master/docs) application of Feliz, which references Feliz and Feliz.Recharts. Changing the children of LineChart.fs to `ReactElement seq` which is used several times throughout the docs app -> still compiles just fine using any of 
```bash
dotnet build
dotnet build -c Release
npm run build # using fable 2.3.3
```
I have dotnet --version 3.0.100 btw

**Comment by cmeeren** [comment]
Oh, it's probably just a discrepancy between Feliz versions. The current Feliz.MaterialUI nuget is made for a lower version than used by @Shmew. Since breaking changes can occur at any time, I should probably lock Feliz.MaterialUI to a specific version of Feliz until Feliz 1.x is released.

I will re-release with updated deps.

**Comment by Zaid-Ajaj** [comment]
What I do with Feliz.Recharts is whenever I publish, I make sure the next version is compatible with latest Feliz, this is my strategy for now till 1.x 

> not sure if it is stupid to do so or not :)

**Comment by cmeeren** [comment]
Yes, I'll remember to do that, too. :)

0.3.1 is in the pipeline.

**Comment by cmeeren** [comment]
@Shmew check out 0.3.1 and feel free to close the issue if the problem is solved.

**Comment by Shmew** [comment]
Yep! That did the trick. Thank you!

**Comment by cmeeren** [comment]
@Zaid-Ajaj FYI: I have now locked the Feliz minor version, under the assumption that minor version bumps may have breaking changes, but patch version bumps never does.
