### ISSUE TITLE
Review: Placement of useMediaQuery

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#3]
I'm unsure where to place [`useMediaQuery`](https://material-ui.com/components/use-media-query/). It doesn't seem to fit with anything else. I have just placed it in a `Hooks` class/file by itself:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Hooks.fs#L17-L24

Does that seem OK?

**Comment by Zaid-Ajaj** [comment]
It does seem OK, putting it in Mui is another option

**Comment by cmeeren** [comment]
That would mean `Mui` contains lots of components and a single hook, so that seems weird too.

Then again - perhaps `Mui` could contain more than just components? What do you think about renaming the `Styles` class `Mui`, so that all the style stuff is also available under `Mui`?

**Comment by cmeeren** [comment]
Keeping it as it is for now.

**Comment by Shmew** [comment]
After having issues with identifying where something should be like in #32 I'm wondering if everything should just be in the `Mui` namespace. I think it would make the library more discover-able, otherwise they have to hunt through docs and try to find which section something is in. This does mean it doesn't as closely follow MUI import statements, but at the same time, if we wanted to write it exactly like that we wouldn't be using a transpiler in the first place ;).

The other issue is that with something like `Styles` I could very easily see that namespace being polluted by other projects. If something else adds to Mui it is almost certainly intentional.

**Comment by cmeeren** [comment]
Thanks! I'll definitely consider it.

**Comment by cmeeren** [comment]
For the record, here is a list of all the relevant stuff that might be moved:

| Old | New | Comment
|-----|------|-----------|
| `Autocomplete.createFilterOptions` | `Mui.createFilterOptions` | Unsure about this since it's specific to a component
| `Hooks.useMediaQuery` | `Mui.useMediaQuery` | Ok
| `Styles.create` (JSS helper) | `Mui.??` | Unsure about this, should be short.
| `Styles.makeStyles` | `Mui.makeStyles` | Ok
| `Styles.useTheme` | `Mui.useTheme` | Ok
| `Styles.createMuiTheme` | `Mui.createMuiTheme` | Ok
| `Styles.responsiveFontSizes` | `Mui.responsiveFontSizes` | Ok

Not relevant: props, `classes`, `themeProps`, and `themeOverrides`.

Input welcome.

**Comment by cmeeren** [comment]
A potential danger of keeping everything under `Mui` is collision. Not likely for the current names, but MUI might in the future get some components that are named the same as some helper functions/hooks/etc.

Furthermore, the only entry points to Feliz.MaterialUI (apart from the ones mentioned below the table) are `Mui`, `Styles`, and `Hooks`. So perhaps moving everything under `Mui` isn't really that necessary as long as all three entry points are clearly documented.

Again, opinions welcome.

**Comment by Shmew** [comment]
I think it's more user friendly to have everything under Mui, but like you said there are dangers. 

For `Styles.create` could it be `Mui.createStyles`?
For `Autocomplete.createFilterOptions` could that not just be an additional overload for `autocomplete.filterOptions`?

**Comment by cmeeren** [comment]
> For `Styles.create` could it be `Mui.createStyles`?

Sure can. Thanks!

> For `Autocomplete.createFilterOptions` could that not just be an additional overload for `autocomplete.filterOptions`?

I assume you are talking about having that overload internally call `createFilterOptions`? I tried that, and it works, but the problem is that then `createFilterOptions` will be called once for each render, which might be expensive (I haven't checked the source too carefully, but it might change anyway), while the intention is to call it once and then use the globally defined (stable) filter function in the render function.

I might be able to solve it with memoization, though. Because an overload is IMHO more dev friendly.

**Comment by cmeeren** [comment]
> I should be able to solve it with memoization, though. Because a prop overload is IMHO more dev friendly.

Dang, I don't think that's possible. One of the arguments (`stringify`) is a function, and AFAIK there's no way to memoize based on that. (Or is there, @Zaid-Ajaj?)

**Comment by Shmew** [comment]
If it's used the same way as `Mui.createStyles` would be, is it a stupid idea to suggest something like `Mui.create` and having methods on that? So we could do something like `Mui.create.styles` or `Mui.create.autocompleteFilterOptions`.

**Comment by cmeeren** [comment]
IMHO that's less discoverable, and you'd need to know of the `Mui.use` and `Mui.create` "entry points" just as much as you'd need to know about the `Hooks` and `Styles` entry points today.

**Comment by Shmew** [comment]
I agree it's less discoverable, just spit-balling ideas.

**Comment by cmeeren** [comment]
Appreciated 👍

**Comment by cmeeren** [comment]
Closing as I'm happy with how it is.
