### ISSUE TITLE
Add links to MaterialUI extensions

### ISSUE THREAD

**Issue by Shmew** [cmeeren/Feliz.MaterialUI#34]
Hey @cmeeren do you think you could add links in your docs to libraries that extend MaterialUI for Feliz? Similar to how the main Feliz repo links to this one? It would help discoverability for some of the libraries I've made for pickers and material-table. At least I think those two would be a good idea since they mention them directly and in some cases (pickers) recommend them over native components.

[Feliz.MaterialUI.Pickers](https://github.com/Shmew/Feliz.MaterialUI.Pickers)
[Feliz.MaterialUI.MaterialTable](https://github.com/Shmew/Feliz.MaterialUI.MaterialTable)

**Comment by cmeeren** [comment]
Thanks! Published: https://cmeeren.github.io/Feliz.MaterialUI/#ecosystem
