### ISSUE TITLE
Docs: please add login page example to demonstrate form fields

### ISSUE THREAD

**Issue by Zaid-Ajaj** [cmeeren/Feliz.MaterialUI#36]
Basically building a replica of this page https://material-ui.com/getting-started/templates/sign-in/ as a full example of using Mui and maybe show-off some validation techniques. 

> Nice to have: use blue accent for the theme and the logo of Fable from [https://fable.io/img/fable_logo.png](https://fable.io/img/fable_logo.png) instead of the lock logo

**Comment by cmeeren** [comment]
Done! I couldn't get theming extension to work (#38), so it's using the default theme for now. I decided to not bother too much about the colors/logo (also, I got the lock icon to transition to a progress bar when "signing in", which was cool).
