### ISSUE TITLE
Review: How to hide internal imports used in inline functions?

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#4]
I'm unsure how to import JS functions that are only used internally (and exposed through other helpers). For example:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Styles.fs#L9-L15

The `StyleImports` module has to be public, since the functions are used in inline members of the `Styles` type:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Styles.fs#L77-L81

I originally tried just using the `import` function directly where it's needed, which worked for single-parameter functions, but not for multi-parameter functions when used like this:

```f#
static member inline makeStyles
    ( getStyles: Theme -> 'a,
      options: MakeStylesOptions
    ) : ('props -> 'a) =
  (StyleImports.makeStyles_getWithOpts (getStyles >> toPlainJsObj), options)
  |> import "makeStyles" "@material-ui/core/styles"
```

I guess this is because the above is calling `makeStyles` with a single tuple argument instead of two arguments. Perhaps there's a workaround using `System.Func`?

It's the same problem here:

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Hooks.fs#L8-L11

And also to some extent here, which also shows a possible workaround - hide the functions from the IDE (the module is still visible, though):

https://github.com/cmeeren/Feliz.MaterialUI/blob/adb43cba1d6b9aea2153da32a9987d608159ed92/src/Feliz.MaterialUI/Mui.fs#L13-L21

**Comment by Zaid-Ajaj** [comment]
maybe having the module be `internal` or `private` could help, i.e.
```
module internal StyleImports  = ...
```

**Comment by cmeeren** [comment]
No, that won't compile either.

**Comment by cmeeren** [comment]
I think perhaps the best method is simply to use

```f#
open System.ComponentModel

[<EditorBrowsable(EditorBrowsableState.Never)>]
// module etc .to be hidden
```
