### ISSUE TITLE
Conflict between nested modules/types?

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#40]
(cc @Zaid-Ajaj)

In the new theme DSL, I have this:

```f#
module theme =

  type palette =
    static member inline primary (color: Color) : IThemeProp = unbox ("palette.primary", color)

  module palette =

    [<Erase>]
    type primary =
      static member inline main (color: string) : IThemeProp = unbox ("palette.primary.main", color)
```

Unfortunately, it seems that for some reason, this does not allow using `theme.palette.primary.main`:

![image](https://user-images.githubusercontent.com/7766733/73140537-45d50e80-407a-11ea-8f2f-4789f3b1467e.png)

Here's a minimal repro:

```f#
module test=

  type a =
    static member inline b x = x

  module a =

    type b =
      static member inline c x = x



// Doesn't compile
let x = test.a.b.c
//               ^ The field, constructor or member 'c' is not defined

// Compiles
open test
let x = a.b.c
```

Does anyone have any idea why, and if it can be circumvented? Currently things aren't looking good for the flattened theme DSL...

**Comment by Zaid-Ajaj** [comment]
Maybe try to define the module `palette` before the type `palette`?

**Comment by Zaid-Ajaj** [comment]
I can't test the following in the REPL but maybe it would help to add `type palette` as an extension type for module `theme` in a different file. i.e.
```fs
// File A
module test =
  module a =
    module b =
      let inline c x = x

// File B
module test = 
    type a = 
        static member inline b x = x

```

**Comment by cmeeren** [comment]
Nope, still fails. (VS gives no error, but Fable compilation fails with the same error.)

**Comment by cmeeren** [comment]
Reported as F# compiler issue here: https://github.com/dotnet/fsharp/issues/8432

**Comment by Shmew** [comment]
Yeah, this is because of the way the compiler resolves types. It picks out the first value that works, which means if you have three levels of nesting it stops working. It's why I had to change the [dsl I used in Feliz.Plotly](https://github.com/Shmew/Feliz.Plotly/issues/8)

**Comment by cmeeren** [comment]
Could you briefly describe how you solved it?

**Comment by Shmew** [comment]
I traversed the schema to find things that were unique and nested them inside the different properties, and everything else was top level. So before it would have been something like:

```fsharp
scatter.font [ 
    scatter.font.size 10 
]

```

where every level of nesting was getting longer, but now it is like this: 

```fsharp
scatter.font [
    font.size 10
]
```

Once I had something that was deeper than three levels (so any more nesting than above) it would stop working and I had to use module aliasing to fix it. Luckily for me almost everything the different charts used were almost the same.

**Comment by cmeeren** [comment]
The only collision are the stuff under `palette`, and I seem to be able to solve it by just renaming the modules. My preferred solution right now:

```f#
theme.palette.primary Colors.indigo  // as normal
theme.palette.primary'.main "#aabbcc"  // note the extra apostrophe
```
