### ISSUE TITLE
Where is the checked propery for radio?

### ISSUE THREAD

**Issue by forki** [cmeeren/Feliz.MaterialUI#41]
![image](https://user-images.githubusercontent.com/57396/76161177-0a296c00-6131-11ea-827f-6751ac4a39cc.png)

I can find a prop.isChecked, but that one is invalid

**Comment by cmeeren** [comment]
It's called `checked'`. Don't you get intellisense for it?

**Comment by Shmew** [comment]
I think that's because he was looking for it in `prop` and not `radio`, and the property is `radio.checked'`

**Comment by cmeeren** [comment]
Oh, right. Feliz.MaterialUI doesn't define anything in `prop`, that's from Feliz.

**Comment by Zaid-Ajaj** [comment]
From `prop` , it is called `prop.isChecked`

**Comment by cmeeren** [comment]
> From `prop` , it is called `prop.isChecked`

That's a different prop. The MUI [Radio](https://material-ui.com/api/radio/) component has a dedicated `checked` prop.

**Comment by forki** [comment]
You lost me.

There is no "checked". could you please try to write a demo. This would also help further generations

**Comment by cmeeren** [comment]
Like this:

![image](https://user-images.githubusercontent.com/7766733/76193607-aceef280-61e4-11ea-887f-185a41e64573.png)

**Comment by forki** [comment]
Ok did not see the prime. Thanks it works but please consider to put it in
the docs. Thanks!

Christer van der Meeren <notifications@github.com> schrieb am Mo., 9. März
2020, 09:02:

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/76202262-dadc3300-61f4-11ea-98f1-e91a0fbb4a1c.png)

seems something is still wrong

**Comment by cmeeren** [comment]
That's a different issue. How are you using `radio.checked'`?

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/76211581-e6d0f080-6206-11ea-8e75-4f08b090e8fc.png)

**Comment by cmeeren** [comment]
Hmm, weird. The code is literally a simple as this, I can't see anything wrong on Feliz.MaterialUI's end here:

![image](https://user-images.githubusercontent.com/7766733/76212001-c6edfc80-6207-11ea-8a78-98d02903716e.png)

My guess is the problem lies elsewhere, but I don't know where. Which versions of Feliz.MaterialUI and `@material-ui/core` are you using?

**Comment by forki** [comment]
Feliz.MaterialUI (0.13.1)
    "@material-ui/core@^4.9.2"

inside of electron

**Comment by cmeeren** [comment]
Can you try replacing `radio.checked' config.SyncImagesOnlyWithWifi` with `prop.custom("checked", config.SyncImagesOnlyWithWifi)`? If that also fails, the error is not in Feliz.MaterialUI.

**Comment by forki** [comment]
ok I'm offically confused now.

As you expected `prop.custom("checked", config.SyncImagesOnlyWithWifi)` did not make it work, BUT `prop.custom("checked", config.SyncImagesOnlyWithWifi = true)` did. So some additional check making it super explicitid that this a bool made it work. Is this a problem with some js prop types lib!? //cc @ncave

**Comment by forki** [comment]
Ok I found the reason. For some reason Sqlite is giving me 1 instead of a true. It never really is a problem because of js truthiness. But here it is. Anyway will try to work around that
