### ISSUE TITLE
Towards v1.0

### ISSUE THREAD

**Issue by cmeeren** [cmeeren/Feliz.MaterialUI#43]
[Feliz is going to 1.0 soon](https://github.com/Zaid-Ajaj/Feliz/issues/148), which means that Feliz.MaterialUI also can go to 1.0.

There are currently no known work items before releasing 1.0. I'm just waiting on Feliz. If anyone want to suggest any breaking changes, now's the time.

**Comment by Shmew** [comment]
Nothing really to add, but I wanted to thank you for all your work on this project! I'll be using this library in production in the coming months and it has made development a breeze.

**Comment by Shmew** [comment]
Hey @cmeeren, 

Feliz 1.0 is now out, whenever you get a chance could you upgrade?

**Comment by cmeeren** [comment]
Thanks for letting me know! I'll try to do it tomorrow, along with updating for the latest MUI packages.

**Comment by cmeeren** [comment]
v1.0.0 is in the pipeline now 🚀
