### ISSUE TITLE
Loosen paket dependencies for FSharp.Core

### ISSUE THREAD

**Issue by Shmew** [cmeeren/Feliz.MaterialUI#45]
The library generates a dependency restriction of `FSharp.Core (>= 4.7.1 && < 4.8.0)`.

Could you adjust it like this:

`nuget FSharp.Core ~> 4.7 lowest_matching: true`

so that it becomes: `FSharp.Core (>= 4.7.0 && < 5.0.0)`

or `~> 4.7.0 lowest_matching: true` if you want it to be `FSharp.Core (>= 4.7.0 && < 4.8.0)`?

**Comment by cmeeren** [comment]
Good catch! I tried your proposed change and did a `dotnet paket install` followed by `dotnet fake build -t CiBuild`, but the .nupkg that is produced still has the same restriction. Am I doing something wrong? Could you send a PR, perhaps?

**Comment by cmeeren** [comment]
Oh wait, I have to do a paket `update`, not `install`. Will fix.
