### ISSUE TITLE
Overriding MuiCssBaseline has incorrect signature

### ISSUE THREAD

**Issue by Shmew** [cmeeren/Feliz.MaterialUI#55]
The current signature of [`theme.overrides.muiCssBaseline.global'`](https://github.com/cmeeren/Feliz.MaterialUI/blob/master/src/Feliz.MaterialUI/ThemeOverrides.fs#L573) takes a list of style properties, where the proper syntax is to set the elements that they apply to:

```javascript
const theme = createMuiTheme({
  overrides: {
    MuiCssBaseline: {
      '@global': {
        html: {
          WebkitFontSmoothing: 'auto',
        },
      },
    },
  },
});
```

I'm not sure how you want to handle this as far as type safety goes, but I can confirm this works:

```fsharp
theme.overrides.muiCssBaseline.global' [
    unbox ("html", (createObj !![
        // styles go here
    ]))
]
```

**Comment by cmeeren** [comment]
Thanks for the report. I haven't had the chance to investigate this yet, and I'm not sure I'll be able to do it this week. It's on my agenda, but I have a lot of other stuff there at the moment. I'll get to it sooner or later. Let me know if you find out what's wrong, or how the signature should be.

**Comment by Shmew** [comment]
No rush! I didn't end up using it, and there's a workaround if I or anyone else comes across it in the meantime.

> Let me know if you find out what's wrong, or how the signature should be.

Well it's really just a matter of if you want to create overloads for all the valid html elements or not. Otherwise `theme.overrides.muiCssBaseline.global': (string * (IStyleProperty list) list` is valid when used with my second snippet.

So that would look like this I believe:

```fsharp
[<Erase>]
type muiCssBaseline =
	static member inline global' (overrides: (string * (IStyleAttribute list)) list) : IThemeProp =
		unbox ("overrides.MuiCssBaseline.@global", createObj !!(overrides |> List.map (fun (k,v) -> k, createObj !!v)))
		
```

**Comment by cmeeren** [comment]
Hmm, but is `string` the only option for the keys? What if you want to override a MUI component?

And I see that `inputBase` also has a `global` name, do you know if that works similarly?

I'm having a hard time finding official MUI docs on this.

**Comment by Shmew** [comment]
This case is specific only to `MuiCssBaseline` AFAIK, and so the keys will only be actual html elements.

**Comment by cmeeren** [comment]
Do you know how the `@global` rule works with `classes`, i.e.

```f#
Mui.cssBaseline [
  cssBaseline.classes.global' "someClassName"
]
```

Is that something that makes sense?

**Comment by Shmew** [comment]
Since `cssBaseline.classes` *only* supports `@global` you can just do it like the normal components: `cssBaseline.classes "someClassName"`.

**Comment by cmeeren** [comment]
Are you mixing `@global` with the `root` class name that all components have? I don't think any components other than `cssBaseline` and `inputBase` has `@global`, so I'm unsure if that's usable in `classes` at all.

**Comment by Shmew** [comment]
I could just be confused, but [this](https://material-ui.com/api/css-baseline/#css) is what I was looking at that gave me that impression.

**Comment by cmeeren** [comment]
I'm thoroughly confused about the class stuff, so I'm leaving that part alone until someone complains.

I have checked in a fix now. Could you give it a try and see?

**Comment by Shmew** [comment]
Yep looks good

**Comment by cmeeren** [comment]
Great, thanks a lot! v1.2.1 is in the pipeline now.
