### ISSUE TITLE
FSharp.Core 5 / .Net5.0 update

### ISSUE THREAD

**Issue by TerenceHinrichsen** [cmeeren/Feliz.MaterialUI#60]
AWESOME Library THANKS!
I use it extensively and it really is a wonderful wrapper.

What is the reason that the nuget package of this great library is constrained to FSharp.Core < 5.0?

**Comment by cmeeren** [comment]
No reason, I'll update.

**Comment by cmeeren** [comment]
v1.2.3 is in the pipeline.
